"""Initial migration

Revision ID: 9ad408a48c40
Revises: 
Create Date: 2026-04-29 15:37:14.009036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ad408a48c40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('plan_tier', sa.String(length=20), nullable=False),
    sa.Column('daily_quota_limit', sa.Integer(), nullable=False),
    sa.Column('daily_quota_used', sa.Integer(), nullable=False),
    sa.Column('quota_reset_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('youtube_url', sa.String(length=500), nullable=False),
    sa.Column('video_id', sa.String(length=20), nullable=False),
    sa.Column('video_title', sa.String(length=500), nullable=True),
    sa.Column('channel_name', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('total_comments', sa.Integer(), nullable=False),
    sa.Column('positive_count', sa.Integer(), nullable=False),
    sa.Column('negative_count', sa.Integer(), nullable=False),
    sa.Column('neutral_count', sa.Integer(), nullable=False),
    sa.Column('positive_pct', sa.Float(), nullable=False),
    sa.Column('negative_pct', sa.Float(), nullable=False),
    sa.Column('neutral_pct', sa.Float(), nullable=False),
    sa.Column('model_accuracy', sa.Float(), nullable=True),
    sa.Column('vader_summary', sa.JSON(), nullable=True),
    sa.Column('model_summary', sa.JSON(), nullable=True),
    sa.Column('top_keyword', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index('ix_analyses_created_at_desc', [sa.literal_column('created_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_video_id'), ['video_id'], unique=False)

    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'analysis_id', name='uq_user_analysis_session')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('preprocessed_text', sa.Text(), nullable=True),
    sa.Column('model_sentiment', sa.String(length=10), nullable=True),
    sa.Column('model_confidence', sa.Float(), nullable=True),
    sa.Column('vader_original_score', sa.Float(), nullable=True),
    sa.Column('vader_original_label', sa.String(length=10), nullable=True),
    sa.Column('vader_processed_score', sa.Float(), nullable=True),
    sa.Column('vader_processed_label', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index('ix_comments_analysis_sentiment', ['analysis_id', 'model_sentiment'], unique=False)

    op.create_table('shared_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('share_token', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shared_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shared_reports_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shared_reports_share_token'), ['share_token'], unique=True)

    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('shared_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shared_reports_share_token'))
        batch_op.drop_index(batch_op.f('ix_shared_reports_analysis_id'))

    op.drop_table('shared_reports')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index('ix_comments_analysis_sentiment')
        batch_op.drop_index(batch_op.f('ix_comments_analysis_id'))

    op.drop_table('comments')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_analysis_id'))

    op.drop_table('chat_sessions')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_video_id'))
        batch_op.drop_index(batch_op.f('ix_analyses_user_id'))
        batch_op.drop_index(batch_op.f('ix_analyses_status'))
        batch_op.drop_index('ix_analyses_created_at_desc')

    op.drop_table('analyses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
